# Form implementation generated from reading ui file 'gui/window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VideoDownload(object):
    def setupUi(self, VideoDownload):
        VideoDownload.setObjectName("VideoDownload")
        VideoDownload.resize(400, 300)
        self.urlEdit = QtWidgets.QLineEdit(parent=VideoDownload)
        self.urlEdit.setGeometry(QtCore.QRect(30, 60, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.urlEdit.setFont(font)
        self.urlEdit.setObjectName("urlEdit")
        self.qualityCombo = QtWidgets.QComboBox(parent=VideoDownload)
        self.qualityCombo.setGeometry(QtCore.QRect(30, 160, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.qualityCombo.setFont(font)
        self.qualityCombo.setObjectName("qualityCombo")
        self.qualityCombo.addItem("")
        self.qualityCombo.addItem("")
        self.qualityCombo.addItem("")
        self.qualityCombo.addItem("")
        self.qualityCombo.addItem("")
        self.downloadButton = QtWidgets.QPushButton(parent=VideoDownload)
        self.downloadButton.setGeometry(QtCore.QRect(110, 250, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.downloadButton.setFont(font)
        self.downloadButton.setObjectName("downloadButton")
        self.progressBar = QtWidgets.QProgressBar(parent=VideoDownload)
        self.progressBar.setGeometry(QtCore.QRect(30, 210, 331, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.videoLabel = QtWidgets.QLabel(parent=VideoDownload)
        self.videoLabel.setGeometry(QtCore.QRect(30, 20, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.videoLabel.setFont(font)
        self.videoLabel.setObjectName("videoLabel")
        self.qualityLabel = QtWidgets.QLabel(parent=VideoDownload)
        self.qualityLabel.setGeometry(QtCore.QRect(30, 120, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.qualityLabel.setFont(font)
        self.qualityLabel.setObjectName("qualityLabel")

        self.retranslateUi(VideoDownload)
        QtCore.QMetaObject.connectSlotsByName(VideoDownload)

    def retranslateUi(self, VideoDownload):
        _translate = QtCore.QCoreApplication.translate
        VideoDownload.setWindowTitle(_translate("VideoDownload", "Dialog"))
        self.urlEdit.setText(_translate("VideoDownload", "https:www.example.com"))
        self.qualityCombo.setItemText(0, _translate("VideoDownload", "480p"))
        self.qualityCombo.setItemText(1, _translate("VideoDownload", "720p"))
        self.qualityCombo.setItemText(2, _translate("VideoDownload", "1080p"))
        self.qualityCombo.setItemText(3, _translate("VideoDownload", "2K"))
        self.qualityCombo.setItemText(4, _translate("VideoDownload", "4K"))
        self.downloadButton.setText(_translate("VideoDownload", "Download"))
        self.videoLabel.setText(_translate("VideoDownload", "Video Downloader"))
        self.qualityLabel.setText(_translate("VideoDownload", "Quality"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VideoDownload = QtWidgets.QMainWindow()
    ui = Ui_VideoDownload()
    ui.setupUi(VideoDownload)
    VideoDownload.show()
    sys.exit(app.exec())
